### ISSUE TITLE
Add a resource section

### ISSUE THREAD

**Issue by ctmbl** [iScsc/blog.iscsc.fr#12]
This is an old idea for the iscsc blog/website: a place where to store interesting resources we may find or give to new users interested into various subject we do!
Non exhaustive list:
- cybersecurity resources
- network
- docker/containerization/virtualization
- various programming language
- useful tools for Linux/Windows system (IDE, DM, editors, shells...)
- other low level subjects: Linux/Windows insides, assembly,...

**Comment by Turtyo** [comment]
Who would be able to add resources ? It might also be interesting to have a way to sort the resources by difficulty levels.

**Comment by ctmbl** [comment]
@Turtyo 
Basically everyone, on the same model as blog posts, see https://iscsc.fr/posts/publish-your-own-post/
And yes sure, we could use tags or special tags to sort them by difficulty

**Comment by Turtyo** [comment]
Yes I see there is already a tagging system with the blog posts. 
How would the resource section be different from the normal posts if everyone can contribute to it ? This feels like a blog post with extra steps for now

**Comment by Turtyo** [comment]
I think we could just have the tagging system as a singular entry point, and list everything under it, updating the list that is shown as the user adds tags (and thus reducing the possibilities).
This would be less confusing than a dual endpoint imo.
I am not sure what the purpose of a json file listing all resources would be, if tag endpoint already does that, could you explain ?

**Comment by ctmbl** [comment]
> I think we could just have the tagging system as a singular entry point, and list everything under it, updating the list that is shown as the user adds tags (and thus reducing the possibilities).

great idea! I'll keep it for sure

>  I am not sure what the purpose of a json file listing all resources would be, if tag endpoint already does that, could you explain ?

You still need somewhere to **store your resources**, something that isn't shown directly to the user but parsed by the website (like a View is different from a Model in the Model-View-Controller framework)
This file can be a big list of entries, yml, json, toml, ...

**Comment by Turtyo** [comment]
Oh I see, this wouldn't be visible to the user, i understand
